-- Wise Bucket M0 foundation.
-- Conventions (all later tables follow them):
--   * everything lives in schema `wb`; read-only views for the LLM live in `wb_views`
--   * ids are uuid (v7, generated by the application); signal times are bigint ns;
--     wall-clock times are timestamptz; flexible values are jsonb
--   * every row carries `rev` from the global sequence `wb.rev_seq`

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS wb;
CREATE SCHEMA IF NOT EXISTS wb_views;

CREATE SEQUENCE IF NOT EXISTS wb.rev_seq;

-- One row per MCP server process (one harness connection).
CREATE TABLE wb.session (
    id             uuid        PRIMARY KEY,
    rev            bigint      NOT NULL DEFAULT nextval('wb.rev_seq'),
    client_name    text,
    client_version text,
    pid            integer     NOT NULL,
    hostname       text,
    cwd            text,
    wb_version     text        NOT NULL,
    started_at     timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now(),
    ended_at       timestamptz
);

CREATE INDEX session_open_idx ON wb.session (last_seen_at) WHERE ended_at IS NULL;

-- The read-only role (managed mode creates it; with your own PostgreSQL it is optional in M0).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wb_reader') THEN
        GRANT USAGE ON SCHEMA wb_views TO wb_reader;
        ALTER DEFAULT PRIVILEGES IN SCHEMA wb_views GRANT SELECT ON TABLES TO wb_reader;
    END IF;
END
$$;
