//! `docs gen [--check]`: generated reference pages.

use std::path::Path;

use wb_core::config::render_configuration_reference;
use wb_core::error::{ErrorKind, Result, err, render_errors_reference};

use crate::cli::Cli;
use crate::ui;

/// Generated pages: (file name, content).
pub fn pages() -> Vec<(&'static str, String)> {
    let cli = clap_markdown::help_markdown::<Cli>();
    vec![
        ("errors.md", render_errors_reference()),
        ("configuration.md", render_configuration_reference()),
        (
            "cli.md",
            format!("<!-- GENERATED by `wisebucket docs gen`. Do not edit by hand. -->\n\n{cli}"),
        ),
    ]
}

pub fn run(out: &Path, check: bool) -> Result<()> {
    let mut stale = Vec::new();
    for (name, content) in pages() {
        let path = out.join(name);
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current == content {
            continue;
        }
        if check {
            stale.push(path.display().to_string());
        } else {
            std::fs::create_dir_all(out)?;
            std::fs::write(&path, content)?;
            ui::ok(format!("wrote {}", path.display()));
        }
    }
    if !stale.is_empty() {
        return Err(err(
            ErrorKind::ConfigInvalid,
            format!(
                "out of date: {} (run `wisebucket docs gen`)",
                stale.join(", ")
            ),
        ));
    }
    if check {
        ui::ok("generated reference pages are up to date");
    }
    Ok(())
}
